
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x89\xdb\x84\xcb\xa9\x7f_3\xc8c[\x84 \xca\xb9\\'
    
_lr_action_items = {'STRING':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[1,-3,-13,1,-14,-2,-4,-12,1,-1,1,1,1,-12,1,-11,1,1,1,-8,-9,]),'SPACE':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[2,-3,-13,2,-14,-2,-4,-12,2,-1,2,2,2,-12,2,-11,2,2,2,-8,-9,]),'QUOTE':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[3,-3,-13,3,-14,-2,-4,-12,3,-1,3,3,3,-12,3,-11,3,3,3,-8,-9,]),'NEWLINE':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[4,-3,-13,4,-14,-2,-4,-12,4,-1,4,4,4,-12,4,-11,4,4,4,-8,-9,]),'NUMBER':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[5,-3,-13,5,-14,-2,-4,-12,5,-1,5,5,5,-12,5,-11,5,5,5,-8,-9,]),'RIGHT_PARENTHESES':([1,2,4,5,6,7,9,12,13,14,15,16,17,18,19,20,],[-3,-13,-14,-2,-4,-12,-1,-7,19,20,-11,-10,-6,-5,-8,-9,]),'BOOLEAN':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[6,-3,-13,6,-14,-2,-4,-12,6,-1,6,6,6,-12,6,-11,6,6,6,-8,-9,]),'LEFT_PARENTHESES':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[8,-3,-13,8,-14,-2,-4,-12,8,-1,8,8,8,-12,8,-11,8,8,8,-8,-9,]),'IDENTIFIER':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[9,-3,-13,9,-14,-2,-4,-12,9,-1,9,9,9,-12,9,-11,9,9,9,-8,-9,]),'$end':([1,2,4,5,6,7,9,10,12,15,16,17,18,19,20,],[-3,-13,-14,-2,-4,-12,-1,0,-7,-11,-10,-6,-5,-8,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expressionlist':([0,3,8,10,11,12,14,16,17,18,],[7,7,13,15,7,15,15,15,7,15,]),'expression':([0,3,8,10,11,12,14,16,17,18,],[10,12,14,16,18,16,16,16,18,16,]),'empty':([0,3,8,10,11,12,14,16,17,18,],[11,11,11,17,11,17,17,17,11,17,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> IDENTIFIER','expression',1,'p_statement_single','/home/zoowii/repos/git/SchemePy/util/lexer.py',76),
  ('expression -> NUMBER','expression',1,'p_statement_single','/home/zoowii/repos/git/SchemePy/util/lexer.py',77),
  ('expression -> STRING','expression',1,'p_statement_single','/home/zoowii/repos/git/SchemePy/util/lexer.py',78),
  ('expression -> BOOLEAN','expression',1,'p_statement_single','/home/zoowii/repos/git/SchemePy/util/lexer.py',79),
  ('expression -> empty expression','expression',2,'p_statement_empty_expr1','/home/zoowii/repos/git/SchemePy/util/lexer.py',84),
  ('expression -> expression empty','expression',2,'p_statement_empty_expr2','/home/zoowii/repos/git/SchemePy/util/lexer.py',89),
  ('expression -> QUOTE expression','expression',2,'p_statement_quote_expr','/home/zoowii/repos/git/SchemePy/util/lexer.py',94),
  ('expression -> LEFT_PARENTHESES expressionlist RIGHT_PARENTHESES','expression',3,'p_statement_form','/home/zoowii/repos/git/SchemePy/util/lexer.py',101),
  ('expression -> LEFT_PARENTHESES expression RIGHT_PARENTHESES','expression',3,'p_statement_form','/home/zoowii/repos/git/SchemePy/util/lexer.py',102),
  ('expressionlist -> expression expression','expressionlist',2,'p_statement_list','/home/zoowii/repos/git/SchemePy/util/lexer.py',123),
  ('expressionlist -> expression expressionlist','expressionlist',2,'p_statement_list','/home/zoowii/repos/git/SchemePy/util/lexer.py',124),
  ('expression -> expressionlist','expression',1,'p_statement_list_exp','/home/zoowii/repos/git/SchemePy/util/lexer.py',137),
  ('empty -> SPACE','empty',1,'p_statement_empty','/home/zoowii/repos/git/SchemePy/util/lexer.py',142),
  ('empty -> NEWLINE','empty',1,'p_statement_empty','/home/zoowii/repos/git/SchemePy/util/lexer.py',143),
]
